CREATE USER IF NOT EXISTS 'dbmba'@'%' IDENTIFIED BY 'dbmba';

CREATE DATABASE IF NOT EXISTS dbmba;

ALTER DATABASE dbmba
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON dbmba.* TO 'dbmba'@'%' IDENTIFIED BY 'dbmba';
